language: php

php:
  - 5.4
  - 5.5
  - hhvm

notifications:
  email: false
  slack:
    secure: N7L2EiGPxoswooDBY3r+D1bxo8rhvqDgn8opRO4xBY+dVe247/VvjWhAXCfXUCROzZhFxi7aU+iBS2vRlxmXd1L5mxCz/B70TQREUlRM6Oo2UhTpY0WBpXV5wwC//q0F1pQLMMODyltvkv6RxCzB/aw7EuSdvQpb/YQT/dBFuio=

before_install:
  - composer selfupdate

install:
  - composer install

before_script:
  - mkdir -p build/logs
  - mysql -e 'create database `harp-orm/random-key`;'
  - mysql harp-orm/random-key < tests/mysql.sql

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - test -e build/logs/clover.xml && wget https://scrutinizer-ci.com/ocular.phar
  - test -e build/logs/clover.xml && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
